import os
import platform
import sys
import shutil

def init(path):

    script_location = os.path.dirname(__file__)
    base_pkg_location = os.path.relpath(script_location, "python_initializer")

    os.mkdir(f"{path}/src")
    os.mkdir(f"{path}/dependencies")

    with open(f"{path}/README",'w') as readme:
        readme.write("Generated by PyX")

    with open(f"{path}/.gitignore", 'w') as gitignore:
        gitignore.write("dependencies/\n__pycache__/")

    with open(f"{path}/buildscript.py", 'w') as buildscript:
        with open(f"{script_location}/scripts/buildscript.copy") as buildscript_copy:
            buildscript.write(buildscript_copy.read())

    with open(f"{path}/runner.py", 'w') as runner:
        with open(f"{script_location}/scripts/runner.copy") as runner_copy:
            runner.write(runner_copy.read())

    shutil.copytree(f"{base_pkg_location}/pyx_build", f"{path}/pyx_build")

    if platform.system() == "Windows":
        with open(f"{path}/pyx.ps1", 'w') as pyx_exec_windows:
            with open(f"{script_location}/windows/pyx.ps1", 'r') as win_batch:
                pyx_exec_windows.write(win_batch.read())

    else:
        with open(f"{path}/pyx.sh", 'w') as pyx_exec_unix:
            with open(f"{script_location}/linux-unix/pyx.sh", 'r') as unix_shell_script:
                pyx_exec_unix.write(unix_shell_script.read())

init(sys.argv[1])
    
